codecov:
  require_ci_to_pass: yes
  require_changes: no

coverage:
  status:
    changes:
      default:
        target: 80%
        threshold: 1%
      patch:
        target: 80%
        threshold: 1%
    project:
      default:
        target: 80%
        threshold: 1%
  precision: 2
  round: down
  range: '80...100'

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: no
